### ISSUE TITLE
Non-ASCII characters messed up

### ISSUE THREAD

**Issue by sidnair** [adicu/Courses#10]
Example:

COCIF1102 Contemporary Civilization
A year-long course designed to introduce students to a wide range of issues of public significance by asking them to read closely texts in various traditions of argument with a focus on selected European traditions of moral, political, religious, and social thought. Readings in the Bible, the Qur�an, Plato, Aristotle, St. Augustine, Machiavelli, Descartes, Hobbes, Locke, Rousseau, Smith, Kant, Marx, Darwin, Nietzsche, DuBois, and Freud.

**Comment by natebrennand** [comment]
Irrelevant until issue #37 is resolved
