### ISSUE TITLE
URL getting too long

### ISSUE THREAD

**Issue by rbtying** [adicu/Courses#119]
Keeping state in the URL is great and all, but it's getting a little too long -- consider structuring data to resolve?

i.e.

http://courses.adicu.com/#/schedule?semester=20141&sections=75423,73956,15011,12794,11638,86848&75423.color=red&73956.color=gray&15011.color=purple&12794.color=green&11638.color=red&86848.color=red&63026.color=green&15011.name=ECONW3213:%20MACROECONOMICS&86848.name=Physics%20Lab&11638.name=COMSW6998:%20MOBILE%20COMPUTER%20VISION

->

http://courses.adicu.com/#/schedule?sem=20141&sec=75423,73956,15011,12794,11638,86848&color=red,gray,purple,green,red,red,green&name=ECONW3213:%20MACROECONOMICS,Physics%20Lab,COMSW6998:%20MOBILE%20COMPUTER%20VISION

Or possibly even more, if we can find a way. base64encode of gzipped metadata?

**Comment by brishin** [comment]
Agreed. I'd like to move to a url scheme where a unique string is generated for each schedule and associated with a cookie - something like

http://courses.adicu.com/#/schedule/u4Ad

which always refers to the correct schedule, even if the user changes their schedule itself. This if course requires some code on the backend to map short URLs to schedules. This would work regardless of logging in, but some auth (either an association with an account or with cookies) should be done to allow editing.

Thoughts @danrschlosser ?
