### ISSUE TITLE
points for some Barnard classes not showing up properly

### ISSUE THREAD

**Issue by janecakemaster** [adicu/Courses#120]
For Barnard dance classes, you get to pick 0, 0.5, or 1 credit for the class. in courses, it shows up as 0 credits. have it default to 1 probably?

**Comment by rbtying** [comment]
This is technically a data issue, or rather, the fact that courses trusts data::coursesv2 endpoint to have useful values (it shouldn't! it should read from the sections directly!).

Fixes will come with a refactor of data to account for different credit values... aka not assuming the most recent upserted value is correct.

**Comment by brishin** [comment]
Closing as this is information that we're just currently not getting.
