### ISSUE TITLE
UX: popup for course info shows up too far down

### ISSUE THREAD

**Issue by janecakemaster** [adicu/Courses#122]
When you click on a course in the calendar view, the info shows up next to the appropriate space in the sidebar. Sometimes the info shows up too far down (see red arrow in pic)  

![screenshot 2014-01-08 18 28 38](https://f.cloud.github.com/assets/1294399/1873652/0eb16650-78bd-11e3-97bd-5e2695024e88.png)

**Comment by G-ram** [comment]
I'll fix this.

**Comment by natebrennand** [comment]
Awesome, when you have an idea of how you're going to go about it can you explain it here before implementation so @brishin can confirm it's a inline with where the code responsible should be?

**Comment by brishin** [comment]
Eh. I can just say. You should scroll to the correct DOM element (popup) in `$scope.selectSection` in `weekView.coffee`. You can use jQuery to do this.

**Comment by G-ram** [comment]
Okay, will do.
