### ISSUE TITLE
Incorrect times? Something is clearly wrong...

### ISSUE THREAD

**Issue by rbtying** [adicu/Courses#145]
Course section times are incorrect (ie 12:40-12:55 PM!?)

**Comment by natebrennand** [comment]
please include the course in question

**Comment by rbtying** [comment]
All of them. (all say 12:40-12:55 or 12:10 pm – 12:25 pm)

**Comment by rbtying** [comment]
Investigation shows data is correct, we introduced a regression somewhere in the display code?

**Comment by natebrennand** [comment]
apparently, we're looking into now
