### ISSUE TITLE
fine-tune calendar dates

### ISSUE THREAD

**Issue by natebrennand** [adicu/Courses#154]
first day: 9/2/2014
last day: 12/8/2014

holidays:
- 11/3/2014
- 11/27/2014
- 11/28/2014

source: http://registrar.columbia.edu/academic-calendar/30

**Comment by brishin** [comment]
@G-ram could you amend your library to support http://www.kanzaki.com/docs/ical/exdate.html
and then use that to exclude the holidays?

**Comment by G-ram** [comment]
Yeah.

**Comment by brishin** [comment]
Holidays still need to be done, start/end fixed.

**Comment by G-ram** [comment]
I just added EXDATE to my library.

**Comment by natebrennand** [comment]
@G-ram, are you going to update the Courses code or should one of us do this issue?

**Comment by G-ram** [comment]
I will update it. In the process of working on it now.
