### ISSUE TITLE
Change "Export to iCal"

### ISSUE THREAD

**Issue by jettca** [adicu/Courses#156]
When I first noticed this, I thought "that's not relevant to me since I use gcal."  If I thought about it for a second longer, I would've been like, obviously I can export an iCal calendar to gcal, but I didn't think about it any longer.

I think this should be made more clear by saying "Export Calendar" and/or including icons for the calendars supported, if those are at all recognizable, so that it's more clear.

**Comment by brishin** [comment]
Fixed e28247a9760a619eeb7cbd5848e847acdeb82f8e
