### ISSUE TITLE
Merge calendar events for batch editing on gcal

### ISSUE THREAD

**Issue by jettca** [adicu/Courses#157]
I don't know if the ical format supports this, but it'd be great if when I imported a TR class into gcal, there was one event for that class.  Currently there are two events for the one class that each repeat weekly and have to be edited separately.  I'd rather it use the gcal option for an event that repeats on select days of the week.

**Comment by brishin** [comment]
Fixed in e28247a9760a619eeb7cbd5848e847acdeb82f8e
