### ISSUE TITLE
Expanded Information in mobile opens modal to the right

### ISSUE THREAD

**Issue by justinxzhao** [adicu/Courses#160]
https://www.dropbox.com/s/qw8jshwgfw29k0v/Screenshot%202014-04-12%2000.03.22.png

Consider popping the information up or maybe make sections expandable?

**Comment by schlosser** [comment]
I'm pretty sure @brishin is working on something like this, no?

**Comment by brishin** [comment]
Yeah, trying to move towards an accordion UI element for the next version of Courses.

**Comment by brishin** [comment]
Preview of what the new UI is going towards. Thoughts @lifeismotley ? @danrschlosser 
![screen shot 2014-04-14 at 17 42 15](https://cloud.githubusercontent.com/assets/920130/2701194/e0bc8d5e-c41d-11e3-84be-2f9bf481f19e.png)

**Comment by brishin** [comment]
Mobile:
![photo apr 14 17 50 18](https://cloud.githubusercontent.com/assets/920130/2701277/e35f103a-c41e-11e3-8da8-ddf4b1a52957.png)

**Comment by justinxzhao** [comment]
Is the Yemini checkbox for the instructor name? And is the reason for the
checkboxes as opposed to radio buttons is that people would want to see
their schedule in the context of multiple PE sections? I'm not sure about
seeing a checkbox for classes that only have one instructor / section...

If there's some way to include the actual sport title for PE courses, that
would be awesome.

I like the reduced font size in the schedule blocks.

And the X only appears if the user opens the accordian? So to delete a
class, the user has to click two times. I suppose that's okay / no better
than it is.

I feel like the font size on the left can be even smaller / reduced / not
bold. Bolding it gives it a less sophisticated feeling? Not sure on this
one.

**Comment by brishin** [comment]
Yemini is instructor name - there will be more info there, but I haven't gotten a chance to implement it yet.

Okay, X is supposed to signify that you can close the accordion. Going to fix that.

The point of the checkbox is that you can remove all the sections from a class without removing the whole class itself.

**Comment by schlosser** [comment]
you should use minimize (dash) and maximize (box) icons for this

**Comment by schlosser** [comment]
or use (plus) for maximize

**Comment by brishin** [comment]
That seems too much like a window though hmm. Plus perhaps. What do you think of the left and right arrows of Finder in list view?

**Comment by schlosser** [comment]
I like the right and downward facing triangles, if that's what you mean

**Comment by brishin** [comment]
No more modal in v0.3.0
