### ISSUE TITLE
bit.ly link for sharing

### ISSUE THREAD

**Issue by jettca** [adicu/Courses#164]
Shorter URLs for sharing will make people more comfortable posting on Facebook/whatever, and sharing is one of our primary selling points.

**Comment by brishin** [comment]
Not opposed to merging this for this semester.
Will close #119

**Comment by schlosser** [comment]
Yeah we definitely should implement something better but for now we should
get this out

**Comment by znewman01** [comment]
@brishin i don't think we should close #119, i think we should leave that open and resolve it by implementing our own shortlinks (possibly when we implement log-ins)

bit.ly then becomes a quick hack for pushing this ASAP

**Comment by brishin** [comment]
I think this is moot now that we have launched v0.3.0 with short urls.
