### ISSUE TITLE
Elasticsearch is slow

### ISSUE THREAD

**Issue by brishin** [adicu/Courses#188]
I suspect it's because of swap thrashing.

Check out http://localhost:9200/_plugin/marvel/kibana/index.html after you've port forwarded.

**Comment by natebrennand** [comment]
just going to make the box much larger.
will be done by Friday

**Comment by brishin** [comment]
It's actually not too bad in prod now, let's plan a scaling strat for the beginning of the semester.

**Comment by natebrennand** [comment]
It's pretty mediocre, and barely anyone is hitting it.

**Comment by rbtying** [comment]
It takes ~1300ms to load for me. We should have <300ms, and ideally 100ms.

**Comment by schlosser** [comment]
Yeah I think we need an upgrade.

**Comment by brishin** [comment]
Load on the data server is around 2.5.

**Comment by schlosser** [comment]
What should we be shooting for?

**Comment by brishin** [comment]
Resolved - migration to new server
