### ISSUE TITLE
Loading indicator for search

### ISSUE THREAD

**Issue by brishin** [adicu/Courses#189]
Should be able to reuse our current loading indicator. Hook into it somehow.

**Comment by schlosser** [comment]
the blue bar?

**Comment by brishin** [comment]
Yes, the blue bar.

**Comment by schlosser** [comment]
I am thinking of doing some css restyling on the results window, and i think we should have a loading/ no results found indicator there.  Thoughts?

**Comment by brishin** [comment]
I'm thinking loading could be the blue bar and then the results not found could be a part of an error/warning notification that is dismissible. I can walk you through some of the technical ideas I have on implementing something like that, if you're interested.

**Comment by schlosser** [comment]
Yeah I'm definitely interested.  I think the best way to dismiss the
results or lack thereof is to either press ESC or click outside the box.
 The former would probably require an external library, and the latter
could be done by tying something like shouldShowResults to the search text
box being active / selected.

What do you think?

**Comment by brishin** [comment]
Maybe we can add a red color to the loading indicator when nothing has been found?

Not sure how much is customizable. Check out my recent diff adding the loading indicator.

The package repo for meteor is here: atmospherejs.com

**Comment by schlosser** [comment]
I think a text message would be better

**Comment by brishin** [comment]
Okay. In that case, you might want to take a look at local-only mongo collections.
