### ISSUE TITLE
Make the weekview more mobile-friendly

### ISSUE THREAD

**Issue by schlosser** [adicu/Courses#192]
We could consider some of the css used in https://github.com/JordanReiter/fullcalendar-mobile, or roll our own.

I think we should have a two-day view that can be scrolled.  Or we could just do an agenda-view.  

Thoughts?

**Comment by natebrennand** [comment]
I think the 2 day view is a great idea. Possibly include a toggle between Mo/Tu & We/Th?

**Comment by schlosser** [comment]
What about friday?  some people do have classes then

**Comment by natebrennand** [comment]
they do exist, but it's an edge case. The proposed toggle could have 3 options as well

**Comment by brishin** [comment]
I don't think showing all of the days in a row would be bad, kind of how the schedule looks on mobile. That or one day view like in iOS cal, but we let users swipe between dates and show what day today is. (iPhone width) Android width keep as is on desktop?

**Comment by brishin** [comment]
Closed in 4905c048ccaf3a5aff679f502da11e3a0f16d53a
