### ISSUE TITLE
Velocity icon in upper right hand corner

### ISSUE THREAD

**Issue by znewman01** [adicu/Courses#194]
IDK what it is but it should go away

**Comment by schlosser** [comment]
ahhhh I thought that was dev only @brishin

**Comment by brishin** [comment]
That's hilarious good catch. That's what I thought too and is sane behavior. :frowning:

**Comment by schlosser** [comment]
I don't know who fixed it but it was fixed!

**Comment by brishin** [comment]
Yeah - solution is to uninstall in production.
