### ISSUE TITLE
We only show max 4 sections of any class

### ISSUE THREAD

**Issue by schlosser** [adicu/Courses#199]
![screen shot 2014-07-30 at 12 59 31 am](https://cloud.githubusercontent.com/assets/2433509/3745243/53f08f88-17a6-11e4-8c1b-73bf622904c9.png)

**Comment by schlosser** [comment]
closed by 414720ec0e2becbfc48fe0f68117694b943dfd3c

**Comment by schlosser** [comment]
@brishin any reason why this was set to four?  Is there a speed / data concern?  or just a bug?

**Comment by brishin** [comment]
No, we used to have a "see more sections" link but I didn't get around to implementing that because of some outstanding bugs.

**Comment by schlosser** [comment]
Lit Hum and CC still show few sections.

**Comment by brishin** [comment]
Going to fix, but it's not the same underlying issue, so closing.
