### ISSUE TITLE
Fall 2014 Mastertask

### ISSUE THREAD

**Issue by brishin** [adicu/Courses#208]
- [x] ES scaling strategy
- [ ] Fix all [hi-pri bugs](https://github.com/adicu/Courses/issues?q=is%3Aopen+is%3Aissue+label%3Ahi-pri)
- [ ] Marketing to freshmen

**Comment by brishin** [comment]
Removing #202 as launch blocking.

**Comment by brishin** [comment]
@natebrennand, are we ready to move over to the new elasticsearch server?

**Comment by natebrennand** [comment]
I still can't get it to fully work locally because the load script seems to be off, but the new ES seems to work properly for search

**Comment by natebrennand** [comment]
it's also in a state where I can easily include additional fields if you would like them.

**Comment by brishin** [comment]
Load script for mongo?

**Comment by natebrennand** [comment]
The same problem as earlier. When I start a fresh project, the data isn't
properly loaded into Mongo for me. Search all works but adding to the
schedule does not display them

**Comment by brishin** [comment]
Okay. Will fix. In the meantime, can you set up nginx to proxy port 80 to ES for the private interface like the old server does?

**Comment by natebrennand** [comment]
@brishin, it's set up the same now
(sorry, was off the grid hiking the past 3 days)

**Comment by brishin** [comment]
@natebrennand Cool, but now it looks like we have no data in this new server:
![screen shot 2014-08-29 at 10 03 52](https://cloud.githubusercontent.com/assets/920130/4091145/600efe2a-2f85-11e4-8095-edd05b5055e3.png)

**Comment by brishin** [comment]
Closing - fall registration has passed
