### ISSUE TITLE
Redirect breaks back button

### ISSUE THREAD

**Issue by mosesn** [adicu/Courses#218]
I clicked a link from http://adicu.com/labs to courses, and couldn't escape back to the original page.  Be a little less aggressive with your back button fixing.

**Comment by schlosser** [comment]
@brishin do you know how to fix this?  It is a pretty big pain

**Comment by schlosser** [comment]
ping @brishin

**Comment by brishin** [comment]
Sorry pset is taking longer than expected, look for something later today.
