### ISSUE TITLE
Redirect is broken on Safari and Firefox

### ISSUE THREAD

**Issue by evantarrh** [adicu/Courses#229]
Refreshing does nothing to load the schedule. Top bar never completes. Same on iOS. 

![screen shot 2014-10-24 at 3 30 25 pm](https://cloud.githubusercontent.com/assets/5566223/4775086/3ccfb502-5bb4-11e4-94e4-ef8f315afc6e.png)

---

![screen shot 2014-10-24 at 3 20 01 pm](https://cloud.githubusercontent.com/assets/5566223/4774964/cfd9ac7e-5bb2-11e4-8b03-2dd2a46f12ef.png)

**Comment by schlosser** [comment]
ping, this is also broken on Chrome.  Refreshing works, but should _not_ be necessary
