### ISSUE TITLE
Export to iCal with proper weekly repetition and semester duration

### ISSUE THREAD

**Issue by lumilux** [adicu/Courses#23]

**Comment by znewman01** [comment]
also gcal

**Comment by janecakemaster** [comment]
currently assigning it to myself, but anyone can jump on it instead,depending on how fast i can get it done

**Comment by G-ram** [comment]
I'll take this as my spring break project.

**Comment by natebrennand** [comment]
That would be amazing! We've been meaning to do this for like 2 years...

**Comment by janecakemaster** [comment]
YASSS
