### ISSUE TITLE
Schedule left sidebar colors sometimes don't match those inside the actual calendar all the time

### ISSUE THREAD

**Issue by gleanawa** [adicu/Courses#241]
This leads to some confusion

**Comment by brishin** [comment]
Could you link a schedule that has this issue?

**Comment by gleanawa** [comment]
Made a random schedule: http://courses.adicu.com/schedule/vtLAAhf7xsWoHNcTb

The colors also repeat

**Comment by brishin** [comment]
Duplicate #207.

Colors repeat by design.
