### ISSUE TITLE
Course points reported as 5 rather than 3.5 or 1.5 

### ISSUE THREAD

**Issue by WordNumber** [adicu/Courses#36]
For example:
http://courses.adicu.com/#20131;10344,18999

I'm not sure if this is a bug or an issue with the data the departments have put up.

**Comment by dashuaige92** [comment]
Fixed.

public/application.js:254

getPoints: function() {
    var points = this.description.match(/\d points/);
    return points ? parseInt(points[0].substring(0,1)) : "Unknown" },

'1.5'.match(/\d points/) = '5'
