### ISSUE TITLE
Some courses are null

### ISSUE THREAD

**Issue by sidnair** [adicu/Courses#4]
Example: ENGLZ1007

**Comment by sidnair** [comment]
The sections aren't null, but the courses have null fields. More examples:

select \* from courses where course_key like 'BUECB%';
+------+-------+------------+-------------+--------+------------+
| id | title | course_key | description | points | updated_at |
+------+-------+------------+-------------+--------+------------+
| 5546 | NULL | BUECB8299 | NULL | NULL | NULL |
| 5547 | NULL | BUECB8210 | NULL | NULL | NULL |
| 5548 | NULL | BUECB8207 | NULL | NULL | NULL |
| 5549 | NULL | BUECB8202 | NULL | NULL | NULL |
| 5550 | NULL | BUECB8201 | NULL | NULL | NULL |
| 5551 | NULL | BUECB7399 | NULL | NULL | NULL |
| 5552 | NULL | BUECB7299 | NULL | NULL | NULL |
| 5553 | NULL | BUECB7203 | NULL | NULL | NULL |
+------+-------+------------+-------------+--------+------------+

**Comment by sidnair** [comment]
This happens when unify does not have the course at all. Not much we can do to fix this. Will add a patch to avoid returning courses with NULL fields to the user.

**Comment by sidnair** [comment]
One solution might be to use a section title as the course title.

**Comment by natebrennand** [comment]
No longer relevant because of Columbia data dumps
