### ISSUE TITLE
courses are not corresponding to results in api

### ISSUE THREAD

**Issue by dinalamdany** [adicu/Courses#42]
if you do a query you get a lot more results than the ones showing on the actual courses page

**Comment by ghost** [comment]
example?

**Comment by dinalamdany** [comment]
Query gray

**Comment by znewman01** [comment]
screenies? can you link from the course directory? i'm still unclear as to what you mean

**Comment by dinalamdany** [comment]
http://data.adicu.com/courses?professor=gray&limit=5&pretty=true&api_token=TOKEN

notice romantic poetry in query but not in screenshot

**Comment by ghost** [comment]
Also notice I did not include my own token

**Comment by znewman01** [comment]
i'm gonna close this, it's a different issue than what you named this one

**Comment by znewman01** [comment]
see #43
