### ISSUE TITLE
Generated files in repo

### ISSUE THREAD

**Issue by znewman01** [adicu/Courses#50]
Right now, .js files are checked into the repo. This is bad practice in general; we should be creating them ourselves to avoid noise (i.e. I have a different version of coffeescript so my generated files look different).

**Comment by ghost** [comment]
Agreed. Will set up a build procedure.
—

**Comment by znewman01** [comment]
Great! Once you do that just let everyone know.

**Comment by ghost** [comment]
Wait, who is logged into the application-development-initiative account?

**Comment by zhemao** [comment]
Oh god, now this is getting confusing. That last one was me. But who was the first?

**Comment by znewman01** [comment]
I assume brishin, it's what happens when you reply to the adi-committee gh
issues emails (which we should turn off)

**Comment by zhemao** [comment]
Blargh, OK, let me figure out how to do that.

**Comment by zhemao** [comment]
I think what was happening is that the notification emails were being sent to infrastructure@adicu.com, and replying to the email replies as that user. I've changed the email for the application-development-initiative user to sgo@adicu.com so that this doesn't happen again.

**Comment by znewman01** [comment]
perfect! Thanks
