### ISSUE TITLE
URL Hash Not Respected

### ISSUE THREAD

**Issue by a2** [adicu/Courses#53]
http://courses.adicu.com/#/schedule#73476,28780,61497,75437,27825,70238 redirects to http://courses.adicu.com/#/schedule

**Comment by natebrennand** [comment]
When I copy/paste that, the second # is replaced by a % which breaks the hash. Anyone know why this happens?

When I fix it, it works

**Comment by a2** [comment]
@nsb2142 When you fix it how?

**Comment by natebrennand** [comment]
http://courses.adicu.com/#/schedule%2373476,28780,61497,75437,27825,70238

Replace the % after schedule with a #, and then the link works

**Comment by a2** [comment]
Did a test. URL hash works in Chrome, Firefox; not in Safari. Using latest versions of each.

**Comment by natebrennand** [comment]
When you copy the link you put in the original post, it works.
But if you click it and follow it, the second '#' is replaced by a % sign.

**Comment by natebrennand** [comment]
Is it standard practice to have > 1 '#' in a URL?
Gmail seems to replace the second # with a % for the link when it auto
generates it.

**Comment by a2** [comment]
I believe it isn't standard practice. See [here](http://stackoverflow.com/a/10851032/205895).

**Comment by natebrennand** [comment]
k, it seems we should change the url hash structure then

**Comment by a2** [comment]
I'd do it myself but I'm in the middle of my UW essay. :disappointed:

**Comment by natebrennand** [comment]
Replaced by #54
