### ISSUE TITLE
modal is too low on screen

### ISSUE THREAD

**Issue by janecakemaster** [adicu/Courses#55]
![Screen Shot 2013-04-15 at 3 19 39 PM](https://f.cloud.github.com/assets/1294399/380736/2ce863a6-a5cf-11e2-9f69-fe465596f5bb.png)

**Comment by znewman01** [comment]
okay this is cause of a missing </div> tag, so the modal winds up being inside of the calendar div. but when i add the closing tag, the remove button stops working
