### ISSUE TITLE
Schedule only takes up 75% of width

### ISSUE THREAD

**Issue by rbtying** [adicu/Courses#68]
Commit 7f8cd9e9 introduces the class large-9 to the schedule body, which has it take up only 75% of the screen (looks a little weird)

![screen shot 2013-07-20 at 4 22 55 pm](https://f.cloud.github.com/assets/918977/831003/5b1b596c-f193-11e2-9466-956ab5a7c973.png)

**Comment by schlosser** [comment]
Bump.  Anyone have any input on this?  We should resolve this issue before school school starts, and ideally with a week or two to spare.

**Comment by rbtying** [comment]
It's easy to fix -- mostly a question of UX design.

**Comment by brishin** [comment]
Whoops. Sorry guys, been doing major work on the site and was going to add a feature there. I'm going to be programming on it today, and I'll change it back if I don't get to adding the feature that I want. Thanks for the heads up.
