### ISSUE TITLE
Short courses don't display in full height.

### ISSUE THREAD

**Issue by schlosser** [adicu/Courses#69]
Courses that aren't 2+ hours don't show all of the text we have to offer (course number, title, credits, and the "Click for more information" text).  From personal experience, I often get my classes mixed up (especially in registration period when my schedule is changing constantly) and maybe course titles should be more prominent than course number.  also, with the way we are doing padding, the cut-off looks awkward.  

![screen shot 2013-08-01 at 7 18 38 pm](https://f.cloud.github.com/assets/2433509/898626/615c69ca-fb1a-11e2-8ce5-282b13fcac74.png)

**Comment by brishin** [comment]
Main issue fixed in d3372e2. Will look into future improvements.
