### ISSUE TITLE
Save history

### ISSUE THREAD

**Issue by sidnair** [adicu/Courses#7]

**Comment by natebrennand** [comment]
Unclear what this is for. I don't think history should be saved until we can call a schedule by URL (issue #39)

**Comment by ghost** [comment]
using localstorage could be cool, right?

**Comment by natebrennand** [comment]
I was under the impression that we did it in the URLs so that they would be easy to share between people. Do I think we want to keep it in the URL. 

If we did both, that could be convenient though

**Comment by ghost** [comment]
right i meant both
