### ISSUE TITLE
The "remove course" "x" overlaps course number on narrow screen sizes

### ISSUE THREAD

**Issue by schlosser** [adicu/Courses#72]
No definitive fix for this, but one idea is to give it a background of some kind that covers the course number behind it.

![screen shot 2013-08-01 at 7 33 30 pm](https://f.cloud.github.com/assets/2433509/898671/81f853c2-fb1c-11e2-9cdc-7b1aca859391.png)

**Comment by znewman01** [comment]
no longer relevant
