### ISSUE TITLE
Remembered courses don't appear

### ISSUE THREAD

**Issue by znewman01** [adicu/Courses#86]
when i add 1004 then refresh, i get this

![2013-10-29-185701_366x156_scrot](https://f.cloud.github.com/assets/873857/1433186/15442ef6-40ed-11e3-9426-2b8490e6c790.png)

**Comment by natebrennand** [comment]
this really needs to be fixed, site is unusable w/o being in incognito mode

**Comment by zhemao** [comment]
Well now the URL just doesn't update at all. This needs to be fixed ASAP.
