### ISSUE TITLE
no way to view course info

### ISSUE THREAD

**Issue by natebrennand** [adicu/Courses#88]
There's no way to view a course's info after it's been added

![screenshot 2013-10-30 14 22 07](https://f.cloud.github.com/assets/2801090/1439802/836b2404-4190-11e3-8940-2c4be6c01979.png)

Clicking on a course also does not yield any course info.

**Comment by brishin** [comment]
Known bug
Edit: you're right, not logged.

**Comment by natebrennand** [comment]
but it's not logged...

**Comment by rbtying** [comment]
Fixed this earlier.
