### ISSUE TITLE
only one way to remove courses

### ISSUE THREAD

**Issue by natebrennand** [adicu/Courses#90]
Currently you have to click a course on the "Current Courses" pane to access a model with has the remove course button.

There should be some way to remove a course w/o opening that pane. If you don't want to re-add the button on the course box in the calendar week, there should be a button on the "Current Course" boxes.

**Comment by brishin** [comment]
This is working as intended. The design is trying to get users to click on the modal.
I think in the future, we're going to work on a workbench feature so just having a remove button may be confusing.
