### ISSUE TITLE
Add support for searching by call number

### ISSUE THREAD

**Issue by zhemao** [adicu/Courses#98]
I've added the functionality for this in data.adicu.com search

http://data.adicu.com/courses/v2/search?api_token=51ffc99d0b18dc0002859b8d&q=66961

However, entering the call number in the search box on the courses website does not give any results.

**Comment by brishin** [comment]
Huh? Shouldn't sending the call number in q work?

**Comment by zhemao** [comment]
It does work. Is that what you're doing in courses? When I enter in the call number, it doesn't find any results and in fact deletes my query from the search box.

**Comment by brishin** [comment]
Ah right. Nevermind. Will fix.
